### ISSUE TITLE
How to import Ktor-Client to implement cross-platform network requests.

### ISSUE THREAD

**Issue by zczhendev** [Kotlin/KMP-App-Template#10]
How to import Ktor-Client to implement cross-platform network requests.

**Comment by zsmb13** [comment]
In this repo, you can find the ktor dependencies being set up here: https://github.com/Kotlin/KMP-App-Template/blob/main/composeApp/build.gradle.kts

It's also covered by the Ktor documentation: https://ktor.io/docs/client-create-and-configure.html

And this tutorial: https://ktor.io/docs/client-create-new-application.html

**Comment by zczhendev** [comment]
Thank you for your answer, but I still need your help。
I follow the steps in the document to add the following message: 

Could not resolve all artifacts for configuration ':composeApp:wasmJsCompileClasspath'.
> Could not resolve io.ktor:ktor-client-core:2.3.11.
  Required by:
      project :composeApp
   > No matching variant of io.ktor:ktor-client-core:2.3.11 was found. The consumer was configured to find a library for use during 'kotlin-api', preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm', attribute 'org.jetbrains.kotlin.wasm.target' with value 'js' but:
       - Variant 'iosArm64ApiElements-published' declares a library for use during 'kotlin-api':
           - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'
           - Other compatible attributes:
               - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
               - Doesn't say anything about org.jetbrains.kotlin.wasm.target (required 'js')
       - Variant 'iosArm64MetadataElements-published' declares a library:
           - Incompatible because this component declares a component for use during 'kotlin-metadata', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed a component for use during 'kotlin-api', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'
           - Other compatible attributes:
               - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
               - Doesn't say anything about org.jetbrains.kotlin.wasm.target (required 'js')

**Comment by zsmb13** [comment]
For Wasm support, you can check out this sample: https://github.com/ktorio/ktor-samples/tree/main/ktor-client-wasm

And for further Ktor-related issues: https://youtrack.jetbrains.com/newIssue?project=KTOR

**Comment by zczhendev** [comment]
Alright, thank you very much
