### ISSUE TITLE
Cannot add Firebase Auth to this template

### ISSUE THREAD

**Issue by murfel** [Kotlin/KMP-App-Template#15]
I've built an example of adding Firebase Auth to the [KMP Wizard](https://kmp.jetbrains.com/#newProject) Android+iOS starter project with shared UI (default settings) and put it into a repo - [murfel/kmp-wizard-firebase-auth/pull/1](https://github.com/murfel/kmp-wizard-firebase-auth/pull/1).

However, when I try the same steps with adding Firebase Auth to this template project, Xcode gives me `No such module 'FirebaseCore'` when I compile the iOS app. The Android app compiles just fine. Please see [murfel/KMP-App-Template-Firebase-Auth/pull/1/files](https://github.com/murfel/KMP-App-Template-Firebase-Auth/pull/1/files)

So basically it doesn't see the Firebase dependency. Funny enough, it doesn't see `FirebaseCore` import, but it does see multiple other Firebase-related imports.

<details>
  <summary>Screenshots</summary>
    <img width="1512" alt="image" src="https://github.com/Kotlin/KMP-App-Template/assets/5155395/5752547f-54c7-4178-842a-32a2f6e74853">
    <img width="1512" alt="image" src="https://github.com/Kotlin/KMP-App-Template/assets/5155395/e85e6419-03b9-454a-9276-96f46f60d838">
</details>

I've created [a diff repo](https://github.com/murfel/KMP-App-Template-KMP-Wizard-Diff/pull/1/files) to compare the difference between the KMP Wizard and this KMP App Template projects. `iosApp/iosApp.xcodeproj/project.pbxproj` is the most promising diff.

I've tried reverting this template's settings to Xcode 14.0 and IPHONEOS_DEPLOYMENT_TARGET to 15.3 (out of things which I understood and could revert), but it didn't help.

This particular change looks funny. Why did you specifically remove Frameworks from buildPhases?

```
buildPhases = (
				F36B1CEB2AD83DDC00CB74D5 /* Compile Kotlin Framework */,
				7555FF77242A565900829871 /* Sources */,
-				B92378962B6B1156000C7307 /* Frameworks */,
				7555FF79242A565900829871 /* Resources */,
```

Do you have any other ideas why it might not be working?

If that's not too much to ask, could you try adding Firebase Auth to your template? Feel free to use [my repo](https://github.com/murfel/KMP-App-Template-Firebase-Auth), `add-firebase-auth` branch. You'd only need to open the iOS app in Xcode, go to File -> Add package dependencies -> enter https://github.com/firebase/firebase-ios-sdk to the search field -> Add Package (wait a few mins) -> Scroll down to only select Firebase Auth.

<details>
  <summary>Screenshots</summary>
    <img width="1512" alt="image" src="https://github.com/Kotlin/KMP-App-Template/assets/5155395/f7c6192a-9dee-4f00-8276-f95a9e661c43">
</details>

Just to check compilation, you don't need to register the app on Firebase, so only [the code from the first commit](https://github.com/murfel/kmp-wizard-firebase-auth/pull/1/commits/dafd58b2b2dbd4810287a0cbafa22ea469b312d7) will suffice. The Android app wouldn't run without registration, but the iOS one will. If the iOS app compiles (just with the `import FirebaseCore`), it means success.

**Comment by murfel** [comment]
Here's a more specific diff of `project.pbxproj` of `KMP Template App + Firebase Auth` over `KMP Wizard + Firebase Auth`

https://gist.github.com/murfel/0f7cc3cd5b606dcd9311110508e4d8e8/revisions

I struggle to decipher which settings to change to receive the same changes in this file since it's an auto-generated file. I think I'm getting there...

**Comment by murfel** [comment]
I minimized the diff it even further, and I found out that in Targets settings -> Build phases, the `Link Binary with Libraries` is missing. But for some reason, when I add Firebase Auth to this section, it just doesn't appear there, and no warning is shown. The quest continues...

<details>
  <summary>Screenshot of KMP Wizard (the correct one)</summary>
<img width="1470" alt="image" src="https://github.com/Kotlin/KMP-App-Template/assets/5155395/339959be-89b2-491d-9873-f4cef13e0924">
</details>

**Comment by zsmb13** [comment]
Thanks for the report! I've updated the Xcode project based on the one currently generated by the wizard, as this one was indeed pretty old. I believe the Firebase dependency should work fine now, but please double-check.

**Comment by murfel** [comment]
It all worked wonderfully, thank you!

https://github.com/murfel/KMP-App-Template-Firebase-Auth-2/pull/1

**Comment by murfel** [comment]
Sorry to nitpick but since you're updating anyway - would it make sense to update AGP to 8.5 as well? Then Xcode needs to be updated to 15.3 to match compatibility.

https://kotlinlang.org/docs/multiplatform-compatibility-guide.html#new-approach-to-auto-generated-targets

These versions are used in the Android Studio KMP App starter project. The only funny thing is that even Android Studio's starter project uses Gradle 8.7 which is beyond what's listed compatible. I'll let it slide for my project, but just worth mentioning.

Also, Android Studio suggests a higher minor version for androidx-ui-tooling - 1.6.8.

**Comment by zsmb13** [comment]
We generally keep the AGP versions here as the latest stable version that Fleet supports. This did get bumped recently, so I've now updated it to 8.4.2.

**Comment by murfel** [comment]
Hmm, I keep getting this message from time to time with 8.4.2. I downgraded to 8.3.2.

I'm on the latest everything - MacBook Air M3, MacOS Catalina 14.5, Android Studio 2024.1.1, and my default happens to be Grade is 8.7.

```
Kotlin Multiplatform <-> Android Gradle Plugin compatibility issue:
The applied Android Gradle Plugin version (8.4.2) is higher 
than the maximum known to the Kotlin Gradle Plugin.
Tooling stability in such configuration isn't tested, please report encountered issues to https://kotl.in/issue

Minimum supported Android Gradle Plugin version: 7.1
Maximum tested Android Gradle Plugin version: 8.3

To suppress this message add 'kotlin.mpp.androidGradlePluginCompatibility.nowarn=true' to your gradle.properties
```

**Comment by zsmb13** [comment]
@murfel This is just a warning, if your build still works, you're probably fine using a newer version of the Android Gradle Plugin than what Kotlin Gradle Plugin knows about.

With Kotlin 2.0.10 we'll have a bump to the Android Gradle Plugin support to 8.5 which should resolve this.

PS. Please open new issues for anything that doesn't relate to the original Firebase problem here - thanks!
